### ISSUE TITLE
NOT AN ISSUE, but idea

### ISSUE THREAD

**Issue by Hammerkirby123** [mrchous/ExternalStartingItems#1]
I'm pretty new to replying on GitHub, so I don't know where to put ideas.

But can you create something similar to the Phedg1's starting items and Bubbet's patch to it, like with points you can unlock and items over time and such?

Also is there a way for you to make it into the GUI similar to Phedg1's?

**Comment by IKEA0x90** [comment]
I am planning to make a mode similar to what you described soon, but I will probably release it as a separate mod. It is a bit different - there are different types of points. Regular ones are awarded on stage completion, red on Mithrix and so on. Different items have different prices that have been balanced by me and my friends over a year of playing.
As for in-game GUI, I'm not planning to do it, unfortunately.

**Comment by Hammerkirby123** [comment]
Ok I was wondering if you could make it very similar to phedg1's since they said they weren't going to work on it and it doesn't seem anyone is going to pick up their gui, so if you could study it and make it like it and maybe have that as a separate mode, I think a lot of people will like that because people wanted someone to pick it up
