### ISSUE TITLE
No idea how to work this

### ISSUE THREAD

**Issue by LittlleJimmy** [mrchous/ExternalStartingItems#2]
Sorry for sounding like a scrub, but I kinda am when it comes to computers. How do I use this? Am I supposed to install it anywhere specific? How will I know if it's working correctly? Again, I apologize, but I read the description like 30 times and it's not clear at all.

**Comment by MGJerry** [comment]
If you have download the mod from a Mod Manager (r2modman for example), just start the game modded and begin a singleplayer run. You don't even have to play the whole run, all the necessary files will be generated after starting that run.

After that, download [this tool from the mod creater](https://github.com/mrchous/ExternalStartingItemsGUI) to change what items you get at the start of the game.

**Comment by LittlleJimmy** [comment]
Ok, but nothing happens before, during, or after starting a run. I'm expecting to be able to choose which items I get to start with. I downloaded the thing, extracted it in my folder of choice, and nothing happens. I have no idea what I'm doing wrong here. There's no application for me to even use. 

Update: I finally found said application after digging around in all the files. Didn't know it was in the bin folder. Sorry, again

**Comment by IKEA0x90** [comment]
This is a github page for the mod. You have to download it either through a mod manager, as MGJerry suggested, or manually. There are a lot of tutorials out there, just google “Ror2 how to install mods”

Then, to select items, you have to get an app. Here is a direct link for the download - https://github.com/mrchous/ExternalStartingItemsGUI/releases/download/v1.0.0.0/ExternalStartingItemsGUI.exe
You get it, start it, and select the items. If the mod is correctly installed, they should be given to you.
